projectTitle = "Dusk Autumn"
modId = "dusk_autumn"
githubRepo = "Teamvoided/DuskBlocks"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "Dusk" , "TheEnderCore" ]
majorMinecraftVersion = "1.21"
minecraftVersion = "1.21.1"
fabricLoaderVersion = "0.16.7"
fabricApiVersion = "0.106.0+1.21.1"
fabricLangKotlinVersion = "1.12.3+kotlin.2.0.21"
license = "MIT"
modules = [ ]
modDescription = ">B("
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = false

[mappings]
    # You have 6 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    type = "QUILT"
    version = "1.21.1+build.3"