projectTitle = "Dusks and Dungeons"
modId = "dusks_and_dungeons"
githubRepo = "Teamvoided/DusksAndDungeons"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "Dusk" , "TheEnderCore" , "RaccoonJohn" , "MincraftEinstein" ]
modVersion = "1.0.0-beta.8"
group = "org.teamvoided"
majorMinecraftVersion = ">=1.21"
minecraftVersion = "1.21.1"
fabricLoaderVersion = "0.19.2"
fabricApiVersion = "0.116.12+1.21.1"
fabricLangKotlinVersion = "1.13.11+kotlin.2.3.21"
license = "MIT"
modules = [ ]
modDescription = "The Best mod out there, there is nothing better. 100/10. Would mod again!"
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = false

[mappings]
    # You have 6 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    type = "MOJANG"
    version = "1.21.1"