mod_name = "Dusks and Dungeons"
mod_id = "dusks_and_dungeons"
mod_group = "org.teamvoided"
mod_version = "1.0.0-beta.8"
mod_description = "The Best mod out there, there is nothing better. 100/10. Would mod again!"
github_repo = "Teamvoided/DusksAndDungeons"
discord_invite = "https://discord.gg/KZ5Q364hEg"
authors = [ "Dusk" , "TheEnderCore" , "RaccoonJohn" , "MincraftEinstein" ]
license = "MIT"
version_range = ">=1.21.1 <1.21.2"
