
package org.teamvoided.voidlib.consortium.block.color

import net.minecraft.block.Blocks
import net.minecraft.block.Blocks.*

@Suppress("unused")
object VanillaColorCollections {
    val CANDLES = FullColorCollections(
        CANDLE,
        WHITE_CANDLE, ORANGE_CANDLE,
        MAGENTA_CANDLE, LIGHT_BLUE_CANDLE,
        YELLOW_CANDLE, LIME_CANDLE,
        PINK_CANDLE, GRAY_CANDLE,
        LIGHT_GRAY_CANDLE, CYAN_CANDLE,
        PURPLE_CANDLE, BLUE_CANDLE,
        BROWN_CANDLE, GREEN_CANDLE,
        RED_CANDLE, BLACK_CANDLE,
    )
    val WOOL = ColorCollection(
        WHITE_WOOL, ORANGE_WOOL,
        MAGENTA_WOOL, LIGHT_BLUE_WOOL,
        YELLOW_WOOL, LIME_WOOL,
        PINK_WOOL, GRAY_WOOL,
        LIGHT_GRAY_WOOL, CYAN_WOOL,
        PURPLE_WOOL, BLUE_WOOL,
        BROWN_WOOL, GREEN_WOOL,
        RED_WOOL, BLACK_WOOL
    )
    val CONCRETE = ColorCollection(
        WHITE_CONCRETE, ORANGE_CONCRETE,
        MAGENTA_CONCRETE, LIGHT_BLUE_CONCRETE,
        YELLOW_CONCRETE, LIME_CONCRETE,
        PINK_CONCRETE, GRAY_CONCRETE,
        LIGHT_GRAY_CONCRETE, CYAN_CONCRETE,
        PURPLE_CONCRETE, BLUE_CONCRETE,
        BROWN_CONCRETE, GREEN_CONCRETE,
        RED_CONCRETE, BLACK_CONCRETE
    )
    val CONCRETE_POWDER = ColorCollection(
        WHITE_CONCRETE_POWDER, ORANGE_CONCRETE_POWDER,
        MAGENTA_CONCRETE_POWDER, LIGHT_BLUE_CONCRETE_POWDER,
        YELLOW_CONCRETE_POWDER, LIME_CONCRETE_POWDER,
        PINK_CONCRETE_POWDER, GRAY_CONCRETE_POWDER,
        LIGHT_GRAY_CONCRETE_POWDER, CYAN_CONCRETE_POWDER,
        PURPLE_CONCRETE_POWDER, BLUE_CONCRETE_POWDER,
        BROWN_CONCRETE_POWDER, GREEN_CONCRETE_POWDER,
        RED_CONCRETE_POWDER, BLACK_CONCRETE_POWDER
    )
    val TERRACOTTA = FullColorCollections(
        Blocks.TERRACOTTA,
        WHITE_TERRACOTTA, ORANGE_TERRACOTTA,
        MAGENTA_TERRACOTTA, LIGHT_BLUE_TERRACOTTA,
        YELLOW_TERRACOTTA, LIME_TERRACOTTA,
        PINK_TERRACOTTA, GRAY_TERRACOTTA,
        LIGHT_GRAY_TERRACOTTA, CYAN_TERRACOTTA,
        PURPLE_TERRACOTTA, BLUE_TERRACOTTA,
        BROWN_TERRACOTTA, GREEN_TERRACOTTA,
        RED_TERRACOTTA, BLACK_TERRACOTTA,
    )
    val GLAZED_TERRACOTTA = ColorCollection(
        WHITE_GLAZED_TERRACOTTA, ORANGE_GLAZED_TERRACOTTA,
        MAGENTA_GLAZED_TERRACOTTA, LIGHT_BLUE_GLAZED_TERRACOTTA,
        YELLOW_GLAZED_TERRACOTTA, LIME_GLAZED_TERRACOTTA,
        PINK_GLAZED_TERRACOTTA, GRAY_GLAZED_TERRACOTTA,
        LIGHT_GRAY_GLAZED_TERRACOTTA, CYAN_GLAZED_TERRACOTTA,
        PURPLE_GLAZED_TERRACOTTA, BLUE_GLAZED_TERRACOTTA,
        BROWN_GLAZED_TERRACOTTA, GREEN_GLAZED_TERRACOTTA,
        RED_GLAZED_TERRACOTTA, BLACK_GLAZED_TERRACOTTA
    )
    val GLASS = FullColorCollections(
        Blocks.GLASS,
        WHITE_STAINED_GLASS, ORANGE_STAINED_GLASS,
        MAGENTA_STAINED_GLASS, LIGHT_BLUE_STAINED_GLASS,
        YELLOW_STAINED_GLASS, LIME_STAINED_GLASS,
        PINK_STAINED_GLASS, GRAY_STAINED_GLASS,
        LIGHT_GRAY_STAINED_GLASS, CYAN_STAINED_GLASS,
        PURPLE_STAINED_GLASS, BLUE_STAINED_GLASS,
        BROWN_STAINED_GLASS, GREEN_STAINED_GLASS,
        RED_STAINED_GLASS, BLACK_STAINED_GLASS,
    )
}