package org.teamvoided.dusk_autumn

import org.teamvoided.dusk_autumn.init.DuskBlocks


val cutoutList = listOf(
    DuskBlocks.CASCADE_SAPLING,
    DuskBlocks.POTTED_CASCADE_SAPLING,
    DuskBlocks.CASCADE_LEAVES,
    DuskBlocks.BLUE_PETALS,
    DuskBlocks.VIOLET_DAISY,
    DuskBlocks.POTTED_VIOLET_DAISY,
    DuskBlocks.GOLDEN_BIRCH_SAPLING,
    DuskBlocks.POTTED_GOLDEN_BIRCH_SAPLING,
    DuskBlocks.GOLDEN_BIRCH_LEAVES,
    DuskBlocks.CASCADE_LEAF_PILE,
    DuskBlocks.OAK_LEAF_PILE,
    DuskBlocks.SPRUCE_LEAF_PILE,
    DuskBlocks.BIRCH_LEAF_PILE,
    DuskBlocks.JUNGLE_LEAF_PILE,
    DuskBlocks.ACACIA_LEAF_PILE,
    DuskBlocks.DARK_OAK_LEAF_PILE,
    DuskBlocks.MANGROVE_LEAF_PILE,
    DuskBlocks.CHERRY_LEAF_PILE,
    DuskBlocks.AZALEA_LEAF_PILE,
    DuskBlocks.FLOWERING_AZALEA_LEAF_PILE,
    DuskBlocks.GOLDEN_BIRCH_LEAF_PILE,
    DuskBlocks.WILD_WHEAT,
    DuskBlocks.GOLDEN_BEETROOTS,
    DuskBlocks.MOONBERRY_VINE,
    DuskBlocks.MOONBERRY_VINELET,

    DuskBlocks.BIG_CHAIN,

    DuskBlocks.OVERGROWN_COBBLESTONE,
    DuskBlocks.OVERGROWN_COBBLESTONE_STAIRS,
    DuskBlocks.OVERGROWN_COBBLESTONE_SLAB,
    DuskBlocks.OVERGROWN_COBBLESTONE_WALL,
    DuskBlocks.OVERGROWN_STONE_BRICKS,
    DuskBlocks.OVERGROWN_STONE_BRICK_STAIRS,
    DuskBlocks.OVERGROWN_STONE_BRICK_SLAB,
    DuskBlocks.OVERGROWN_STONE_BRICK_WALL,

    DuskBlocks.ROCKY_GRASS,
    DuskBlocks.ROCKY_PODZOL,
    DuskBlocks.ROCKY_MYCELIUM,
    DuskBlocks.ROCKY_DIRT_PATH,
    DuskBlocks.ROCKY_DIRT,
    DuskBlocks.ROCKY_COARSE_DIRT,
    DuskBlocks.ROCKY_MUD,
    DuskBlocks.ROCKY_SNOW,
    DuskBlocks.ROCKY_GRAVEL,
    DuskBlocks.ROCKY_SAND,
    DuskBlocks.ROCKY_RED_SAND,
    DuskBlocks.ROCKY_SOUL_SAND,
    DuskBlocks.ROCKY_SOUL_SOIL,
    DuskBlocks.SLATED_GRASS,
    DuskBlocks.SLATED_PODZOL,
    DuskBlocks.SLATED_MYCELIUM,
    DuskBlocks.SLATED_DIRT_PATH,
    DuskBlocks.SLATED_DIRT,
    DuskBlocks.SLATED_COARSE_DIRT,
    DuskBlocks.SLATED_MUD,
    DuskBlocks.SLATED_SNOW,
    DuskBlocks.SLATED_GRAVEL,
    DuskBlocks.SLATED_SAND,
    DuskBlocks.SLATED_RED_SAND,
    DuskBlocks.SLATED_SOUL_SAND,
    DuskBlocks.SLATED_SOUL_SOIL,
    DuskBlocks.BLACKSTONE_GRASS,
    DuskBlocks.BLACKSTONE_PODZOL,
    DuskBlocks.BLACKSTONE_MYCELIUM,
    DuskBlocks.BLACKSTONE_DIRT_PATH,
    DuskBlocks.BLACKSTONE_DIRT,
    DuskBlocks.BLACKSTONE_COARSE_DIRT,
    DuskBlocks.BLACKSTONE_MUD,
    DuskBlocks.BLACKSTONE_SNOW,
    DuskBlocks.BLACKSTONE_GRAVEL,
    DuskBlocks.BLACKSTONE_SAND,
    DuskBlocks.BLACKSTONE_RED_SAND,
    DuskBlocks.BLACKSTONE_SOUL_SAND,
    DuskBlocks.BLACKSTONE_SOUL_SOIL
)
