package org.teamvoided.dusks_and_dungeons.init.misc

import net.minecraft.world.level.block.Blocks
import net.minecraft.world.level.block.Blocks.*
import net.minecraft.world.level.block.SoundType
import net.minecraft.world.level.block.state.BlockBehaviour.OffsetType
import net.minecraft.world.level.block.state.BlockBehaviour.Properties
import net.minecraft.world.level.block.state.BlockBehaviour.Properties.ofFullCopy
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument
import net.minecraft.world.level.material.MapColor
import net.minecraft.world.level.material.PushReaction
import org.teamvoided.dusks_and_dungeons.util.block.cornSyrupBlockSound
import org.teamvoided.dusks_and_dungeons.util.block.luminance
import org.teamvoided.dusks_and_dungeons.util.block.rootBlockSound

//(ender) This file should not reference DnDBlocks
object DnDBlockSettings {
    val ICE: Properties = ofFullCopy(Blocks.ICE)

    val WARPED_WART: Properties = Properties.of()
        .mapColor(MapColor.WARPED_STEM)
        .noCollission()
        .randomTicks()
        .sound(SoundType.NETHER_WART)
        .pushReaction(PushReaction.DESTROY)
    val CORN_SYRUP: Properties = ofFullCopy(HONEY_BLOCK)
        .mapColor(MapColor.PODZOL)
        .sound(cornSyrupBlockSound)
    val ROOT_BLOCK: Properties = Properties.of()
        .mapColor(MapColor.PODZOL)
        .instrument(NoteBlockInstrument.BASS)
        .strength(0.7f)
        .noOcclusion()
        .isSuffocating(Blocks::never)
        .isViewBlocking(Blocks::never)
        .ignitedByLava()
        .sound(rootBlockSound)
    val WILD_WHEAT: Properties = Properties.of()
        .mapColor(MapColor.PLANT)
        .noCollission()
        .instabreak()
        .sound(SoundType.CROP)
        .offsetType(OffsetType.XZ)
        .pushReaction(PushReaction.DESTROY)
    val GOLDEN_BEETROOT: Properties = Properties.of()
        .mapColor(MapColor.GOLD)
        .noCollission()
        .randomTicks()
        .instabreak()
        .sound(SoundType.CROP)
        .pushReaction(PushReaction.DESTROY)

    // Wood Types
    val CASCADE_SAPLING: Properties = Properties.of()
        .mapColor(MapColor.COLOR_RED)
        .noCollission()
        .randomTicks()
        .instabreak()
        .sound(SoundType.CHERRY_SAPLING)
        .pushReaction(PushReaction.DESTROY)
    val CASCADE_LEAVES: Properties = Properties.of()
        .strength(0.2f)
        .randomTicks()
        .noOcclusion()
        .isValidSpawn(Blocks::ocelotOrParrot)
        .isSuffocating(Blocks::never)
        .isViewBlocking(Blocks::never)
        .ignitedByLava()
        .pushReaction(PushReaction.DESTROY)
        .isRedstoneConductor(Blocks::never)
        .sound(SoundType.AZALEA_LEAVES)
        .mapColor(MapColor.COLOR_RED)
    val CASCADE_WOOD: Properties = Properties.of()
        .mapColor(MapColor.COLOR_BROWN)
        .instrument(NoteBlockInstrument.BASS)
        .strength(2.0f)
        .sound(SoundType.CHERRY_WOOD)
        .ignitedByLava()
    val STRIPPED_CASCADE_WOOD: Properties = ofFullCopy(STRIPPED_CHERRY_WOOD).mapColor(MapColor.COLOR_BLUE)
    val CASCADE_PLANKS: Properties = Properties.of()
        .mapColor(MapColor.COLOR_BLUE)
        .instrument(NoteBlockInstrument.BASS)
        .strength(2.0F, 3.0F)
        .sound(SoundType.CHERRY_WOOD)
        .ignitedByLava()
    val BLUE_DOOR: Properties = Properties.of()
        .mapColor(MapColor.COLOR_BLUE)
        .instrument(NoteBlockInstrument.BASS)
        .strength(3.0f)
        .noOcclusion()
        .ignitedByLava()
        .pushReaction(PushReaction.DESTROY)
    val VERDANT_WOOD: Properties = ofFullCopy(Blocks.OAK_WOOD)
    val STRIPPED_VERDANT_WOOD: Properties = ofFullCopy(Blocks.STRIPPED_OAK_WOOD)
    val VERDANT_PLANKS: Properties = ofFullCopy(Blocks.OAK_PLANKS)
    val GOLDEN_MUSHROOM_BLOCK: Properties = ofFullCopy(BROWN_MUSHROOM_BLOCK).mapColor(MapColor.GOLD)
    val GOLDEN_MUSHROOM: Properties = Properties.of()
        .mapColor(MapColor.GOLD)
        .noCollission()
        .randomTicks()
        .instabreak()
        .sound(SoundType.GRASS)
        .luminance(11)
        .offsetType(OffsetType.XYZ)
        .hasPostProcess(Blocks::always)
        .pushReaction(PushReaction.DESTROY)

    val TINTED_SANDSTONE: Properties = Properties.of()
        .mapColor(MapColor.WATER)
        .instrument(NoteBlockInstrument.BASEDRUM)
        .requiresCorrectToolForDrops()
        .strength(0.8f)

    // Fun!
    fun petals(color: MapColor): Properties = ofFullCopy(PINK_PETALS).mapColor(color)
    fun vivions(color: MapColor): Properties = petals(color).sound(SoundType.NETHER_SPROUTS)
    fun corn(): Properties = Properties.of()
        .mapColor(MapColor.PLANT)
        .noCollission()
        .instabreak()
        .sound(SoundType.CROP)
        .pushReaction(PushReaction.DESTROY)

    fun moonbery(): Properties = Properties.of()
        .mapColor(MapColor.COLOR_PURPLE)
        .noCollission()
        .strength(0.2f)
        .sound(SoundType.CAVE_VINES)
        .ignitedByLava()
        .pushReaction(PushReaction.DESTROY)

    fun smallPumpkin(color: MapColor): Properties = Properties.of()
        .mapColor(color)
        .strength(1.0f)
        .sound(SoundType.WOOD)
        .pushReaction(PushReaction.DESTROY)
}
